services:
  
  db:
    image: postgres:15.5-alpine3.19
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@password.com
      - PGADMIN_DEFAULT_PASSWORD=password